//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrud.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Profile
    {
        public int imageID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public string imageData { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
