//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrud.Models.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminsModel
    {
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage ="Invalid Firstname")]
        [Required(ErrorMessage ="Can't Leave field Empty")]
        public string firstname { get; set; }

        [RegularExpression(@"^[a-zA-Z]*$", ErrorMessage = "Invalid Lastname")]
        [Required(ErrorMessage ="Can't Leave field Empty")]
        public string lastname { get; set; }

        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [Required(ErrorMessage ="Can't Leave field Empty")]
        public string email { get; set; }

        [Phone(ErrorMessage = "Invalid Phone Number")]
        [Required(ErrorMessage ="Can't Leave field Empty")]
        public string phoneNumber { get; set; }

        [Required(ErrorMessage ="Can't Leave field Empty")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,20}$", ErrorMessage = "must contain at least one special character, uppercase letter, lowercase letter, one digit")]
        public string og_pass { get; set; }

        [Compare("og_pass", ErrorMessage = "Password Does Not Match")]
        [Required(ErrorMessage ="Can't Leave field Empty")]
        public string cnf_pass { get; set; }
    }
}
